services:
  postgres:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=something_secret
      - POSTGRES_DB=tictactoe
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "9091:9091"
      - "9092:9092"
    environment:
      - DB_SOURCE=postgresql://root:something_secret@postgres:5432/tictactoe?sslmode=disable
      - GRPC_SERVER_ADDRESS=api:9091
      - WEBSOCKET_SERVER_ADDRESS=api:9092
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
  
  gateway-envoy:
    build:
      context: .
      dockerfile: Dockerfile.envoy
    ports:
      - '8080:8080'
    depends_on:
      - api

volumes:
  data-volume: