// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID             int64       `json:"id"`
	HostUserID     pgtype.Int8 `json:"host_user_id"`
	Status         string      `json:"status"`
	CurrentState   pgtype.Text `json:"current_state"`
	NextTurnUserID pgtype.Int8 `json:"next_turn_user_id"`
}

type GameParticipant struct {
	ID     int64       `json:"id"`
	GameID pgtype.Int8 `json:"game_id"`
	UserID pgtype.Int8 `json:"user_id"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
